sudo: false

language: node_js
node_js:
  - 6
  - 7

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S+)?$/

cache:
  directories:
    - demo/node_modules
    - node_modules

script:
  - npm run coverage -- --no-cache --runInBand

after_script:
  - npm run coverage:report
